services:
  webapp:
    build:
      context: ./webapp/
      dockerfile: Dockerfile
    container_name: webapp
    volumes:
      - ./data:/data
      - ./secret:/etc/secret
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp
    networks:
      - app-network
  
  db:
    image: mongo:latest
    hostname: test_mongodb
    env_file:
      - ./secret/mongopass.env
    container_name: db
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/conf:/data/configdb
      
    ports:
      - 27017:27017
    networks:
      - app-network
    

networks:
  app-network:
    driver: bridge